/* MTI_DPI */

/*
 * Copyright 2002-2021 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"

#ifndef MTI_INCLUDED_TYPEDEF_env_t
#define MTI_INCLUDED_TYPEDEF_env_t

typedef struct {
    short bis;
    char es;
}  env_t;

#endif

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fadd(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fsub(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fmul(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fdiv(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fma(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    const svBitVecVal* op3,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fms(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    const svBitVecVal* op3,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fnma(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    const svBitVecVal* op3,
    int rounding_mode,
    const env_t* env);
    
DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fnms(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    const svBitVecVal* op3,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fmin_max(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fsqrt(
    svBitVecVal* result,
    const svBitVecVal* op,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fcmp(
	svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fsgnj(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const svBitVecVal* op2,
    int rounding_mode,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fmv_f2x(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const env_t* env,
    int nchunks);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fclass(
    svBitVecVal* result,
    const svBitVecVal* op1,
    const env_t* env);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fcvt_f2i(
    svBitVecVal* result,
    const svBitVecVal* op1,
    int rounding_mode,
    const env_t* env,
    int is_signed,
    int int_format);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fcvt_i2f(
    svBitVecVal* result,
    const svBitVecVal* op1,
    int rounding_mode,
    const env_t* env,
    int is_signed,
    int int_format);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_fcvt_f2f(
    svBitVecVal* result,
    const svBitVecVal* op1,
    int rounding_mode,
    const env_t* src_env,
    const env_t* dst_env);
#endif 
